import type { RevisionPage, RevisionTheme } from './types';

type Texts = [prompt: string, correct: string, wrong1: string, wrong2: string];
type Item = { ca: Texts; fr: Texts; why: string };
const q = (ca: Texts, fr: Texts, why: string): Item => ({ ca, fr, why });
const p = (title: string, kicker: string, facts: string[], tip: string, words: [string, string][], grammar: [string, string, string, string]): RevisionPage => ({ title, kicker, facts, tip, words, grammar: { title: grammar[0], rule: grammar[1], ca: grammar[2], fr: grammar[3] } });
function make(id: string, title: string, icon: string, subtitle: string, categories: string[], bankIds: string[], articles: string, pages: RevisionPage[], items: Item[][]): RevisionTheme {
  return { id, title, icon, subtitle, color: 'neutral', categories, bankIds, articles, pages,
    sources: id === 'code-expert' ? 'Sélection des pièges non visuels de questions.json : exceptions, conditions cumulées, mécanique. Difficulté éditoriale, sans classement statistique des erreurs.' : 'Vocabulaire et constructions de quizz.json et questions.json, développés en exercices de compréhension.',
    links: id === 'catala-suite' ? [{ title: 'CPNL · Les pronoms febles', url: 'https://www.cpnl.cat/gramatica/66/37-els-pronoms-febles/nivell/basic-2' }] : id === 'catala-phrases' ? [{ title: 'CPNL · Les pronoms relatius', url: 'https://www.cpnl.cat/gramatica/60/39-els-pronoms-relatius/nivell/tots' }] : [],
    questions: items.flatMap((rows, page) => rows.map(({ ca, fr, why }, i) => ({ id: `${id}-${page + 1}-${i + 1}`, page, prompt: ca[0], answers: ca.slice(1), correct: 0, explanation: why, french: { prompt: fr[0], answers: fr.slice(1) } }))) };
}

export const extraThemes: RevisionTheme[] = [
  make('code-expert', 'Code expert & pièges', '🧩', 'Les exceptions qui changent toute la réponse.', ['PRIORITY', 'OVERTAKING', 'PARKING', 'VEHICLE'], ['9709', '9527', '9595', '1292', '9511', '9608', '9734', '8247', '9315', '7594'], '13, 15, 26–28, 33', [
    p('Priorités : reconnaître le cas particulier', 'RÈGLE → EXCEPTION → DÉTAIL DÉCISIF', [
      'Sans signalisation, la priorité à droite connaît des **exceptions** : les véhicules sur rails passent avant les autres, même lorsqu’ils arrivent de la gauche.',
      'Toujours sans signalisation, une **voie revêtue est prioritaire sur une voie non revêtue**. Une route générale prime aussi sur une route de catégorie inférieure : ne regarde pas uniquement la droite.',
      'Dans un rétrécissement sans signalisation spécifique, le **véhicule entré le premier** passe d’abord. La largeur insuffisante empêche les deux véhicules de se croiser normalement.',
      'Si l’ordre d’arrivée est incertain, privilégie le véhicule qui a **le plus de difficultés à manœuvrer**. Sa taille et ses caractéristiques comptent, pas seulement son nom « camion » ou « autobus ».',
      'Si les véhicules sont du même type dans ce cas de doute, celui qui devrait **reculer le plus loin** a la priorité. L’autre libère le passage.',
      'Sur un passage étroit à **forte pente, le véhicule qui monte** est prioritaire. Le Code retient une pente d’au moins **7 %** ; si l’inclinaison est incertaine, on revient aux critères précédents.'
    ], 'Procède comme un tri : **signalisation ? pente ? premier engagé ? difficulté de manœuvre ?** Une règle générale ne suffit pas si la question ajoute une exception.', [['estretall', 'rétrécissement'], ['retrocedir', 'reculer'], ['ascendent / descendent', 'qui monte / qui descend']], ['En cas de dubte', 'En cas de dubte signifie « en cas de doute ». Ce groupe annonce un critère de remplacement lorsque le premier ne permet pas de décider.', 'En cas de dubte, té prioritat el vehicle amb més dificultats de maniobra.', 'En cas de doute, le véhicule qui a le plus de difficultés à manœuvrer est prioritaire.']),
    p('Dépasser : lire toutes les conditions', 'UNE EXCEPTION N’EST PAS UN DROIT ABSOLU', [
      'Un véhicule a nettement ralenti pour tourner ou s’arrêter **à gauche** : un dépassement par la droite peut être autorisé. Il faut toujours disposer de l’espace et de la sécurité nécessaires.',
      'Dans une circulation dense où chaque file avance au rythme de ses véhicules, une file plus rapide **n’effectue pas un dépassement au sens de cette règle**. Cela n’autorise pas à slalomer entre les files.',
      'En ville, le dépassement par la droite demande **au moins deux voies dans le même sens, délimitées par des marques**, et une manœuvre sans danger. Le seul mot « ville » ne suffit pas.',
      'Au sommet ou dans un virage peu visible, l’exception demande des **sens clairement délimités** et une manœuvre **sans empiéter sur le sens opposé**. Une seule condition remplie ne suffit pas.',
      'À un carrefour, une exception existe si la chaussée bénéficie d’une **priorité expressément signalée**. Une priorité supposée ne suffit pas. Les ronds-points et certains passages par la droite sont d’autres cas prévus.',
      'La ligne continue connaît une exception encadrée pour contourner un véhicule immobilisé qui bloque la voie, **hors embouteillage et sans danger**. Des conditions identiques encadrent le passage de certains usagers lents, dont les cyclistes : ce n’est jamais automatique.'
    ], 'Souligne mentalement les **ET** : priorité **et** panneau ; obstacle immobilisé **et** absence de danger. N’oublie pas le « sauf » : un véhicule arrêté dans un bouchon n’est pas l’obstacle de cette exception.', [['envair', 'empiéter / envahir'], ['aglomeració de trànsit', 'embouteillage'], ['expressament', 'expressément']], ['Sempre que… i…', 'Sempre que introduit ici une condition. Avec i (« et »), plusieurs exigences se cumulent : il faut vérifier chacune avant de choisir « oui ».', 'Només si és segur i es compleixen les condicions.', 'Seulement si c’est sûr et si les conditions sont remplies.']),
    p('Mécanique et pente : les détails trompeurs', 'L’ÉTAT DE LA PÉDALE · LE BON SEUIL', [
      'Enfoncer la pédale d’embrayage signifie **débrayer** : le mouvement du moteur n’est plus transmis à la boîte par l’embrayage. **Embragatge acoblat** désigne au contraire l’embrayage accouplé, pédale relâchée.',
      'Les roues **motrices reçoivent l’effort du moteur** ; les roues **directrices orientent le véhicule**. Dans une question sur le placement contre la bordure, cherche donc les roues directrices.',
      'Pour laisser une voiture à boîte manuelle en pente, coupe le moteur, serre le frein de stationnement et engage **la première en montée, la marche arrière en descente**. La vitesse engagée ne remplace pas le frein.',
      'Le calage supplémentaire en pente sensible concerne les véhicules de **plus de 3 500 kg**, les autobus et les ensembles de véhicules. « Plus de » n’inclut pas une voiture seule d’exactement 3 500 kg.',
      'Dans ce cas, utilise une **cale prévue pour cet usage, pas une pierre**. L’alternative prévue est l’appui d’une roue directrice à la bordure : orientée vers le centre en montée, vers l’extérieur en descente.',
      'Au début d’une forte descente, choisis un rapport suffisamment bas pour conserver le **frein moteur**. Le point mort retire cette aide ; freiner continuellement peut faire surchauffer les freins.'
    ], 'Le piège est souvent un seul détail : **pédale enfoncée**, **montée ou descente**, **exactement ou plus de**. Lis ce détail avant de choisir une réponse mécanique qui semble familière.', [['desembragar', 'débrayer'], ['trava', 'cale'], ['rodes directrius', 'roues directrices']], ['Més de / exactament', 'Més de donne un seuil strict. Exactament désigne la valeur elle-même : 3 500 n’est pas plus de 3 500. Vérifie aussi les autres catégories citées.', 'Més de 3.500 kg no vol dir exactament 3.500 kg.', 'Plus de 3 500 kg ne signifie pas exactement 3 500 kg.'])
  ], [
    [
      q(["Sense senyals de prioritat, un tramvia s’apropa per l’esquerra. Qui passa primer?","El tramvia.","Nosaltres, perquè ve de l’esquerra.","Nosaltres, si la nostra calçada és més ampla."], ["Sans signalisation de priorité, un tramway arrive de gauche. Qui passe en premier ?","Le tramway.","Nous, car il arrive de gauche.","Nous, si notre chaussée est plus large."], 'Les véhicules sur rails constituent une exception à la priorité à droite.'),
      q(['Sense senyals, una via pavimentada es creua amb una via sense pavimentar. Quina té preferència?', 'La pavimentada.', 'Sempre la de la dreta.', 'Sempre la més estreta.'], ['Sans signalisation, une voie revêtue croise une voie non revêtue. Laquelle est prioritaire ?', 'La voie revêtue.', 'Toujours celle de droite.', 'Toujours la plus étroite.'], 'Il faut repérer la nature des deux voies, pas uniquement leur position.'),
      q(['En un estretall sense senyals ni gran pendent, un vehicle ja hi ha entrat. Qui té preferència?', 'El que hi ha accedit primer.', 'Sempre el més pesant.', 'Sempre el que ve per la dreta.'], ['Dans un rétrécissement sans panneaux ni forte pente, un véhicule est déjà engagé. Qui est prioritaire ?', 'Celui qui est entré le premier.', 'Toujours le plus lourd.', 'Toujours celui de droite.'], 'Le premier engagé est le premier critère de ce cas.'),
      q(["Dos vehicles arriben alhora a un estretall sense senyals ni gran pendent. Quin té preferència?","El que té més dificultats de maniobra.","El que circula en sentit descendent.","El que té més espai per retrocedir."], ["Deux véhicules arrivent ensemble à un rétrécissement sans panneaux ni forte pente. Lequel est prioritaire ?","Celui qui a le plus de difficultés à manœuvrer.","Celui qui roule dans le sens de la descente.","Celui qui a le plus de place pour reculer."], 'L’arrivée simultanée conduit à comparer les difficultés de manœuvre.'),
      q(['En un estretall sense senyals ni gran pendent, es dubta de qui ha arribat primer. Si els vehicles són del mateix tipus, quin té preferència?', 'El que hauria de retrocedir més distància.', 'El que hauria de retrocedir menys.', 'Sempre el que baixa.'], ['Dans un rétrécissement sans panneaux ni forte pente, on ignore qui est arrivé le premier. Si les véhicules sont du même type, lequel est prioritaire ?', 'Celui qui devrait reculer le plus loin.', 'Celui qui devrait reculer le moins loin.', 'Toujours celui qui descend.'], 'À type égal, la plus longue marche arrière est évitée.'),
      q(["En un tram estret sense senyals i amb un pendent del 9 %, qui té preferència?","El vehicle que puja.","El que baixa, per la seva distància de frenada.","El que hauria de retrocedir més distància, encara que baixi."], ["Dans un passage étroit sans panneaux avec une pente de 9 %, qui est prioritaire ?","Le véhicule qui monte.","Celui qui descend, à cause de sa distance de freinage.","Celui qui devrait reculer le plus loin, même s’il descend."], '9 % est une forte pente : la règle spécifique donne priorité au véhicule montant.'),
      q(["Quina inclinació mínima activa la regla de gran pendent en un pas estret?","7 %.","5 %.","10 %."], ["Quelle inclinaison minimale déclenche la règle de forte pente dans un passage étroit ?","7 %.","5 %.","10 %."], 'Le Code retient une inclinaison minimale de 7 %.')
    ], [
      q(["El vehicle precedent ha reduït molt la marxa per girar a l’esquerra. El podem avançar per la dreta?","Sí, si hi ha espai i es pot fer sense perill.","No, fora de zona urbana sempre cal passar per l’esquerra.","Només quan ja s’hagi aturat completament."], ["Le véhicule devant a beaucoup ralenti pour tourner à gauche. Peut-on le dépasser par la droite ?","Oui, avec suffisamment de place et sans danger.","Non, hors agglomération il faut toujours passer à gauche.","Seulement lorsqu’il est déjà complètement arrêté."], 'C’est un cas prévu, mais l’espace et la sécurité restent nécessaires.'),
      q(["Amb circulació densa, cada carril avança al ritme dels vehicles precedents. Un carril més ràpid fa necessàriament un avançament?","No, en aquesta situació no es considera avançament.","Sí, encara que el vehicle no canviï de carril.","Només deixa de ser avançament quan el carril més ràpid és el dret."], ["Dans une circulation dense, chaque file suit le rythme des véhicules devant. Une file plus rapide effectue-t-elle nécessairement un dépassement ?","Non, dans ce cas ce n’est pas considéré comme un dépassement.","Oui, même si le véhicule ne change pas de voie.","Cela cesse d’être un dépassement uniquement lorsque la file la plus rapide est celle de droite."], 'Une file qui avance plus vite dans un bouchon n’autorise pas à slalomer.'),
      q(["En zona urbana, quina combinació permet l’avançament per la dreta estudiat?","Dos carrils o més del mateix sentit, marcats, i cap perill.","Una calçada prou ampla per a dues files, encara que els carrils no estiguin marcats.","Dos carrils marcats en total, encara que un sigui de sentit contrari."], ["En ville, quelles conditions permettent le dépassement par la droite étudié ?","Au moins deux voies du même sens, marquées, et aucun danger.","Une chaussée assez large pour deux files, même sans voies marquées.","Deux voies marquées au total, même si l’une est en sens opposé."], 'Il faut lire les conditions ensemble, pas retenir seulement « en ville ».'),
      q(["En un revolt amb poca visibilitat, quines condicions exigeix l’excepció per avançar?","Sentits clarament delimitats i no envair el contrari.","Sentits delimitats, encara que envaïm breument el contrari.","No veure cap vehicle de cara, encara que els sentits no estiguin delimitats."], ["Dans un virage peu visible, quelles conditions exige l’exception permettant de dépasser ?","Des sens clairement délimités et aucun empiètement sur le sens opposé.","Des sens délimités, même si l’on empiète brièvement sur le sens opposé.","Ne voir aucun véhicule en face, même si les sens ne sont pas délimités."], 'L’exception cumule séparation claire et maintien hors du sens opposé.'),
      q(["Per avançar en una intersecció emparant-nos en l’excepció de prioritat, n’hi ha prou amb suposar que som prioritaris?","No, la prioritat ha d’estar expressament senyalitzada.","Sí, si no s’acosta cap vehicle per la dreta.","Sí, si la nostra via és més ampla que l’altra."], ["Pour dépasser à une intersection en invoquant l’exception de priorité, suffit-il de supposer qu’on est prioritaire ?","Non, cette priorité doit être expressément signalée.","Oui, si aucun véhicule n’arrive de droite.","Oui, si notre voie est plus large que l’autre."], 'La priorité et sa signalisation expresse sont deux éléments à vérifier.'),
      q(["Un cotxe està aturat en un embús davant d’una línia contínua. Podem aplicar l’excepció del vehicle immobilitzat per passar-lo?","No, l’aglomeració de trànsit queda exclosa.","Sí, si veiem prou lluny i no s’acosta ningú.","Sí, quan el vehicle porta més de dos minuts aturat."], ["Une voiture est arrêtée dans un bouchon devant une ligne continue. Peut-on appliquer l’exception du véhicule immobilisé pour la passer ?","Non, l’embouteillage est exclu.","Oui, si nous voyons assez loin et que personne n’arrive.","Oui, lorsque le véhicule est arrêté depuis plus de deux minutes."], 'Un obstacle immobilisé et une file arrêtée dans un bouchon ne relèvent pas du même cas.'),
      q(["Hi ha un ciclista lent, una línia contínua i poca visibilitat. El tipus d’usuari és suficient per aplicar l’excepció i passar-lo?","No, encara cal comprovar que la maniobra no comporta perill.","Sí, perquè l’excepció depèn únicament de la baixa velocitat del ciclista.","Sí, si activem l’intermitent abans de trepitjar la línia."], ["Il y a un cycliste lent, une ligne continue et peu de visibilité. Le type d’usager suffit-il à appliquer l’exception pour le passer ?","Non, il faut encore vérifier que la manœuvre ne présente aucun danger.","Oui, car l’exception dépend uniquement de la faible vitesse du cycliste.","Oui, si nous mettons le clignotant avant de franchir la ligne."], 'L’exception est soumise à des conditions ; elle ne permet pas de forcer le passage.')
    ], [
      q(["En un vehicle manual, què passa quan premem completament el pedal de l’embragatge?","Es desconnecta la transmissió del moviment del motor a la caixa de canvis.","Es connecta la transmissió del moviment del motor a la caixa de canvis.","El motor s’atura, però continua connectat a la caixa de canvis."], ["Sur un véhicule manuel, que se passe-t-il lorsqu’on enfonce complètement la pédale d’embrayage ?","La transmission du mouvement du moteur à la boîte de vitesses est interrompue.","La transmission du mouvement du moteur à la boîte de vitesses est établie.","Le moteur s’arrête, mais reste relié à la boîte de vitesses."], 'Pédale enfoncée = débrayé : l’embrayage interrompt cette transmission.'),
      q(["Quines rodes orientem quan la norma de calatge en pendent parla de recolzar una roda contra la vorada?","Les directrius.","Les motrius, encara que no siguin directrius.","Les posteriors, independentment del sistema de direcció."], ["Quelles roues oriente-t-on lorsque la règle de calage en pente prévoit un appui contre la bordure ?","Les roues directrices.","Les roues motrices, même si elles ne sont pas directrices.","Les roues arrière, quel que soit le système de direction."], 'Directrices = direction ; motrices = effort moteur.'),
      q(["Deixem un turisme manual estacionat en pujada. Quina marxa afegim al fre d’estacionament?","La primera.","La marxa enrere, perquè el cotxe podria retrocedir.","El punt mort, perquè el fre ja immobilitza el vehicle."], ["Nous laissons une voiture manuelle garée en montée. Quel rapport ajoute-t-on au frein de stationnement ?","La première.","La marche arrière, car la voiture pourrait reculer.","Le point mort, car le frein immobilise déjà le véhicule."], 'Montée : première. Le frein de stationnement reste nécessaire.'),
      q(["Amb el motor apagat i el fre d’estacionament aplicat, quina marxa deixem en un turisme manual estacionat en baixada?","La marxa enrere.","La primera, igual que en pujada.","Qualsevol marxa endavant, indistintament."], ["Moteur coupé et frein de stationnement serré, quel rapport laisse-t-on sur une voiture manuelle garée en descente ?","La marche arrière.","La première, comme en montée.","N’importe quel rapport de marche avant, indifféremment."], 'Descente : marche arrière, moteur coupé et frein de stationnement.'),
      q(["Un turisme sol té exactament 3.500 kg de MMA. Què podem deduir del criteri «més de 3.500 kg» de la regla de calatge?","Que no compleix aquest llindar estricte; les altres precaucions continuen vigents.","Que el compleix, perquè «més de» inclou la igualtat.","Que queda exempt de posar el fre d’estacionament en pendent."], ["Une voiture seule a exactement 3 500 kg de MMA. Que peut-on déduire du critère « plus de 3 500 kg » de la règle de calage ?","Qu’elle n’atteint pas ce seuil strict ; les autres précautions restent applicables.","Qu’elle le remplit, car « plus de » inclut l’égalité.","Qu’elle est dispensée de serrer le frein de stationnement en pente."], 'Un seuil strict exclut sa valeur exacte ; cela ne supprime pas les autres précautions de stationnement.'),
      q(["Per complir l’obligació específica de calatge en pendent, podem fer servir una pedra?","No; cal una trava adequada o l’alternativa prevista amb una roda directriu a la vorada.","Sí, si la pedra és prou gran i el vehicle no es mou.","Sí, sempre que també deixem una marxa engranada."], ["Pour respecter l’obligation spécifique de calage en pente, peut-on utiliser une pierre ?","Non ; il faut une cale adaptée ou l’alternative prévue avec une roue directrice contre la bordure.","Oui, si la pierre est assez grosse et que le véhicule ne bouge pas.","Oui, à condition de laisser aussi un rapport engagé."], 'La cale doit être prévue pour cet usage. Une pierre n’est pas un dispositif adapté.'),
      q(["En una baixada forta i llarga, quina opció conserva el fre motor?","Una marxa adequada engranada, amb l’embragatge acoblat.","La mateixa marxa, però amb el pedal d’embragatge premut tota l’estona.","El punt mort, mantenint el motor encès."], ["Dans une forte et longue descente, quelle option conserve le frein moteur ?","Un rapport adapté engagé, avec l’embrayage accouplé.","Le même rapport, mais avec la pédale d’embrayage enfoncée en permanence.","Le point mort, en gardant le moteur allumé."], 'Choisis le rapport dès le début de la descente ; les freins peuvent surchauffer s’ils sont sollicités continuellement.')
    ]
  ]),
  make('catala-confusions', 'Català · mots à ne pas confondre', '🔎', 'Des mots voisins, des actions différentes.', ['CATALA'], [], '', [
    p('Une lettre peut changer la scène', 'VOIR · BOIRE · SUIVRE · ÊTRE SÛR', [
      '**Veure** signifie voir ; **beure** signifie boire. Dans une question de visibilité, cherche le V de voir : veure un obstacle veut dire voir un obstacle.',
      '**Seguir** signifie suivre ou continuer ; **segur** signifie sûr. Seguir un vehicle décrit une action, alors que un lloc segur décrit un endroit sans danger.',
      '**Parar** signifie arrêter ; **parlar** signifie parler. Le L supplémentaire change l’action : parar el motor signifie arrêter le moteur, pas lui parler.',
      '**Aparcar** signifie garer ; **aparèixer** signifie apparaître. Un obstacle peut aparèixer devant toi ; une voiture peut aparcar sur une place.',
      '**Calçada** désigne la chaussée ; **calçat**, dans un contexte de roues, signifie calé. Le mot calçat peut aussi désigner les chaussures : le contexte tranche.',
      '**Vora** est le bord, **vorera** le trottoir et **voral** l’accotement. Associe chacun à une position précise plutôt que de traduire les trois par « côté ».'
    ], 'Fais une petite scène mentale : **je VOIS = VEURE ; je BOIS = BEURE**. Pour SEGUR, pense « sécurité » ; pour SEGUIR, imagine une voiture qui en suit une autre.', [['veure / beure', 'voir / boire'], ['seguir / segur', 'suivre / sûr'], ['parar / parlar', 'arrêter / parler']], ['Verbe ou description ?', 'Un infinitif désigne une action : seguir. Un adjectif décrit un nom : segur dans un lloc segur. Cherche le rôle du mot avant de traduire toute la phrase.', 'Podem seguir el vehicle si és segur.', 'Nous pouvons suivre le véhicule si c’est sûr.']),
    p('Le véhicule, ses gestes et ses dimensions', 'ACTION → OBJET → MESURE', [
      '**Pujar / baixar** signifient monter / descendre ; **apujar / abaixar** signifient augmenter / baisser quelque chose. Baixar del cotxe décrit une personne qui descend de voiture.',
      '**Posar / treure** signifient mettre / enlever. Posar el cinturó et treure el cinturó demandent deux gestes opposés : attacher la ceinture et l’enlever.',
      '**Llarg / ample / alt** signifient long / large / haut. Les mesures associées sont **llargada / amplada / alçada** : longueur, largeur et hauteur.',
      '**Llum** signifie lumière ou feu d’éclairage ; **llarg** signifie long. Llums de carretera décrit les feux de route, sans donner la longueur de la route.',
      '**Espatlla** est l’épaule ; **espatllar-se** signifie tomber en panne ou s’abîmer. Un motor espatllat est un moteur en panne, pas une pièce située à l’épaule.',
      '**Desplaçar-se** signifie se déplacer ; **desplaçament** est le déplacement. **Frenar** est freiner ; **frenada** est le freinage. Le nom désigne l’action ou son résultat.'
    ], 'Mémorise en paires de gestes : **POSAR, je mets ; TREURE, je retire**. Pour les dimensions, imagine trois flèches : longueur devant toi, largeur sur les côtés, hauteur vers le ciel.', [['posar / treure', 'mettre / enlever'], ['alçada / amplada', 'hauteur / largeur'], ['espatllat', 'en panne / abîmé']], ['De l’action au nom', 'Une question peut utiliser le verbe ou le nom associé : frenar / frenada, desplaçar-se / desplaçament. Le changement de forme ne crée pas une nouvelle manœuvre.', 'Abans de frenar, anunciem una frenada important.', 'Avant de freiner, nous annonçons un freinage important.'])
  ], [
    [
      q(['Quina acció expressa «veure un obstacle»?', 'Percebre’l amb els ulls.', 'Beure aigua.', 'Moure l’obstacle.'], ['Quelle action exprime « veure un obstacle » ?', 'Le percevoir avec les yeux.', 'Boire de l’eau.', 'Déplacer l’obstacle.'], 'Veure = voir ; beure = boire.'),
      q(['A «un lloc segur», què significa «segur»?', 'Sense perill.', 'Seguir un cotxe.', 'Continuar caminant.'], ['Dans « un lloc segur », que signifie « segur » ?', 'Sans danger.', 'Suivre une voiture.', 'Continuer à marcher.'], 'Segur décrit un endroit ; seguir est le verbe suivre.'),
      q(['Quin verb significa continuar darrere d’un vehicle?', 'Seguir.', 'Beure.', 'Aparcar.'], ['Quel verbe signifie continuer derrière un véhicule ?', 'Suivre.', 'Boire.', 'Garer.'], 'Seguir un vehicle = suivre un véhicule.'),
      q(['«Parar el motor» vol dir…', 'Aturar el motor.', 'Parlar amb algú.', 'Encendre el motor.'], ['« Parar el motor » veut dire…', 'Arrêter le moteur.', 'Parler avec quelqu’un.', 'Allumer le moteur.'], 'Parar n’est pas parlar : repère le L supplémentaire.'),
      q(['Un obstacle «apareix» a la calçada. Què passa?', 'L’obstacle es fa visible.', 'El conductor aparca.', 'La calçada desapareix.'], ['Un obstacle « apareix » sur la chaussée. Que se passe-t-il ?', 'L’obstacle apparaît.', 'Le conducteur se gare.', 'La chaussée disparaît.'], 'Aparèixer = apparaître ; aparcar = garer.'),
      q(['Quina expressió parla de la superfície per on circulen els vehicles?', 'La calçada.', 'El calçat.', 'L’espatlla.'], ['Quelle expression désigne la surface où circulent les véhicules ?', 'La chaussée.', 'Les chaussures.', 'L’épaule.'], 'Calçada désigne la chaussée ; el calçat désigne les chaussures. Employé comme adjectif, calçat peut aussi signifier calé.'),
      q(['Quin espai lateral, normalment elevat i destinat als vianants, anomenem així?', 'La vorera.', 'El voral.', 'La calçada.'], ['Comment appelle-t-on cet espace latéral, généralement surélevé et destiné aux piétons ?', 'Le trottoir.', 'L’accotement.', 'La chaussée.'], 'Vorera = trottoir ; voral = accotement ; calçada = chaussée. Les mots proches ne désignent pas le même espace.')
    ], [
      q(['Què vol dir «baixar del cotxe»?', 'Sortir del vehicle.', 'Augmentar-ne l’alçada.', 'Reparar el motor.'], ['Que veut dire « baixar del cotxe » ?', 'Descendre du véhicule.', 'Augmenter sa hauteur.', 'Réparer le moteur.'], 'Baixar del cotxe décrit le fait de descendre de voiture.'),
      q(['Quin verb és el contrari de «posar» en «posar el cinturó»?', 'Treure.', 'Veure.', 'Seguir.'], ['Quel verbe s’oppose à « posar » dans « posar el cinturó » ?', 'Enlever.', 'Voir.', 'Suivre.'], 'Posar = mettre ; treure = enlever.'),
      q(['Quina mesura correspon a «alçada»?', 'L’altura.', 'L’amplada.', 'La llargada.'], ['À quelle mesure correspond « alçada » ?', 'La hauteur.', 'La largeur.', 'La longueur.'], 'Alçada se rapporte à alt : haut.'),
      q(['Quina paraula descriu un vehicle de gran llargada?', 'Llarg.', 'Llum.', 'Estret.'], ['Quel mot décrit un véhicule de grande longueur ?', 'Long.', 'Lumière.', 'Étroit.'], 'Llarg = long ; llum = lumière.'),
      q(['Un motor «espatllat» està…', 'Avariat.', 'A l’espatlla del conductor.', 'Necessàriament encès.'], ['Un moteur « espatllat » est…', 'En panne.', 'Sur l’épaule du conducteur.', 'Forcément allumé.'], 'Espatllat renvoie à une panne ou à une détérioration ; espatlla est l’épaule.'),
      q(['Quin nom correspon a l’acció de «frenar»?', 'Frenada.', 'Finestra.', 'Fermesa.'], ['Quel nom correspond à l’action de « frenar » ?', 'Freinage.', 'Fenêtre.', 'Fermeté.'], 'Frenar est le verbe ; frenada est le nom du freinage.'),
      q(['Què descriu un «desplaçament lateral»?', 'Un moviment cap a un costat.', 'Una avaria del motor.', 'La llum del sostre.'], ['Que décrit un « desplaçament lateral » ?', 'Un mouvement vers un côté.', 'Une panne du moteur.', 'La lumière du toit.'], 'Desplaçament est le nom associé à se déplacer ; lateral précise la direction.')
    ]
  ]),
  make('catala-suite', 'Català · la suite', '🌱', 'Pronoms, temps et petites nuances nouvelles.', ['CATALA'], [], '', [
    p('Ces petits mots remplacent quoi ?', 'HI · EN · HO · EL / LA / ELS / LES', [
      '**Hi** peut remplacer un lieu déjà cité : anem al garatge → hi anem. On dit « nous y allons » au lieu de répéter le garage.',
      '**En** peut remplacer une provenance introduite par de : sortim del túnel → en sortim. Le français utilise souvent « en » lui aussi : nous en sortons.',
      '**En** sert aussi avec une quantité : tens cadenes ? En tinc dues. On conserve le nombre deux sans répéter le nom chaînes.',
      '**Ho** reprend une idée ou une chose non nommée précisément : no ho sé = je ne le sais pas. Ici, « le » reprend ce qui vient d’être demandé.',
      '**El, la, els, les** peuvent remplacer un objet précis. Veig el senyal → el veig ; veig les marques → les veig. Le genre et le nombre donnent un indice.',
      'Un pronom attaché à l’infinitif garde sa fonction : **entrar-hi** = y entrer, **sortir-ne** = en sortir, **comprovar-ho** = vérifier cela. Cherche ce dont on parlait juste avant.'
    ], 'Pense **HI = ici ou là ; EN = en sortir ou en avoir ; HO = cela**. Ce sont des repères pour ces exemples, pas une traduction unique valable dans toutes les phrases.', [['entrar-hi', 'y entrer'], ['sortir-ne', 'en sortir'], ['comprovar-ho', 'vérifier cela']], ['Trouver le mot remplacé', 'Lis le groupe cité avant le pronom. Dans al garatge → hi, il s’agit d’un lieu ; dans del túnel → en, il s’agit d’une provenance.', 'Anem al garatge. Hi anem a peu.', 'Nous allons au garage. Nous y allons à pied.']),
    p('Déjà, encore, à nouveau : situer l’action', 'UNE ACTION PEUT COMMENCER, CONTINUER OU CESSER', [
      '**Ja** signifie déjà ; **encara** signifie encore. Ja està aturat dit que l’arrêt a eu lieu ; encara circula dit que le véhicule continue de rouler.',
      '**Encara no** signifie pas encore. **Ja no** signifie ne… plus. Le premier attend un changement ; le second indique qu’une situation a cessé.',
      '**Tornar a + infinitif** signifie faire à nouveau. Tornar a mirar demande de regarder une nouvelle fois, pas forcément de revenir en arrière physiquement.',
      '**Acabar de + infinitif** peut dire « venir de faire ». Acaba de frenar signifie qu’il vient de freiner : l’action est toute récente.',
      '**Deixar de + infinitif** signifie cesser de faire. Deixar de circular est arrêter de circuler, alors que deixar passar signifie laisser passer quelqu’un.',
      '**Mentre** signifie pendant que et relie deux actions simultanées. Mentre esperem, observem décrit une observation pendant l’attente, pas seulement après.'
    ], 'Dessine une mini-frise : **encara no = pas encore arrivé ; ja = déjà arrivé ; ja no = c’est fini**. Pour tornar a, imagine une flèche qui répète la même action.', [['encara no / ja no', 'pas encore / ne… plus'], ['tornar a', 'à nouveau'], ['mentre', 'pendant que']], ['Le petit mot change le temps', 'Encara no et ja no contiennent tous deux no, mais ne racontent pas la même situation. Place l’action sur une ligne du temps avant de répondre.', 'Encara no ha sortit. / Ja no és aquí.', 'Il n’est pas encore sorti. / Il n’est plus ici.'])
  ], [
    [
      q(['A «Anem al garatge. Hi anem», què substitueix «hi»?', 'Al garatge.', 'El conductor.', 'Dues rodes.'], ['Dans « Anem al garatge. Hi anem », que remplace « hi » ?', 'Au garage.', 'Le conducteur.', 'Deux roues.'], 'Hi reprend ici le lieu où l’on va.'),
      q(['A «Sortim del túnel. En sortim», què indica «en»?', 'Del túnel.', 'Cap al túnel.', 'Dues vegades.'], ['Dans « Sortim del túnel. En sortim », que désigne « en » ?', 'Du tunnel.', 'Vers le tunnel.', 'Deux fois.'], 'En reprend une provenance introduite par de.'),
      q(['«Tens cadenes? En tinc dues.» Quantes cadenes té?', 'Dues.', 'Cap.', 'No s’indica cap quantitat.'], ['« Tens cadenes? En tinc dues. » Combien de chaînes a-t-il ?', 'Deux.', 'Aucune.', 'Aucune quantité n’est indiquée.'], 'En remplace cadenes ; dues conserve la quantité.'),
      q(['Què significa «No ho sé»?', 'No sé això.', 'No hi ha cap lloc.', 'No tinc dues coses.'], ['Que signifie « No ho sé » ?', 'Je ne sais pas cela.', 'Il n’y a aucun lieu.', 'Je n’ai pas deux choses.'], 'Ho reprend ici l’idée ou l’information demandée.'),
      q(['A «Veig el senyal. El veig», què substitueix «el»?', 'El senyal.', 'La carretera.', 'Les marques.'], ['Dans « Veig el senyal. El veig », que remplace « el » ?', 'Le panneau.', 'La route.', 'Les marques.'], 'El reprend un objet précis masculin singulier : el senyal.'),
      q(['A «Veig les marques. Les veig», a què es refereix «les»?', 'A les marques.', 'Al senyal.', 'Al lloc on anem.'], ['Dans « Veig les marques. Les veig », à quoi renvoie « les » ?', 'Aux marques.', 'Au panneau.', 'Au lieu où nous allons.'], 'Les reprend le féminin pluriel les marques.'),
      q(['Què vol dir «comprovar-ho»?', 'Comprovar això.', 'Comprar un vehicle.', 'Entrar en un lloc.'], ['Que veut dire « comprovar-ho » ?', 'Vérifier cela.', 'Acheter un véhicule.', 'Entrer dans un lieu.'], 'Le pronom ho est attaché à l’infinitif comprovar.')
    ], [
      q(['El vehicle «ja està aturat». Què sabem?', 'Que s’ha aturat.', 'Que encara circula.', 'Que no ha començat a frenar mai.'], ['Le véhicule « ja està aturat ». Que sait-on ?', 'Qu’il est déjà arrêté.', 'Qu’il roule encore.', 'Qu’il n’a jamais commencé à freiner.'], 'Ja = déjà : l’arrêt est réalisé.'),
      q(['El vehicle «encara no ha sortit». Què significa?', 'Que no ha sortit fins ara.', 'Que ja ha marxat.', 'Que no tornarà mai.'], ['Le véhicule « encara no ha sortit ». Que signifie la phrase ?', 'Qu’il n’est pas encore sorti.', 'Qu’il est déjà parti.', 'Qu’il ne reviendra jamais.'], 'Encara no = pas encore, sans affirmer « jamais ». '),
      q(['«Ja no circula» vol dir…', 'Que ha deixat de circular.', 'Que continua circulant.', 'Que encara no ha començat a existir.'], ['« Ja no circula » veut dire…', 'Qu’il ne circule plus.', 'Qu’il continue à circuler.', 'Qu’il n’a pas encore commencé à exister.'], 'Ja no = ne… plus : la situation a cessé.'),
      q(['Què demana «tornar a mirar»?', 'Mirar una altra vegada.', 'Fer marxa enrere obligatòriament.', 'Deixar de mirar.'], ['Que demande « tornar a mirar » ?', 'Regarder à nouveau.', 'Faire obligatoirement marche arrière.', 'Cesser de regarder.'], 'Tornar a + infinitif exprime une répétition.'),
      q(['«Acaba de frenar» situa la frenada…', 'En un passat molt recent.', 'Només en el futur.', 'En una acció que no passarà.'], ['« Acaba de frenar » situe le freinage…', 'Dans un passé tout récent.', 'Seulement dans le futur.', 'Dans une action qui n’arrivera pas.'], 'Acabar de peut exprimer « venir de faire ». '),
      q(['Què significa «deixar de circular»?', 'Cessar la circulació.', 'Circular de nou.', 'Deixar passar un altre vehicle necessàriament.'], ['Que signifie « deixar de circular » ?', 'Cesser de circuler.', 'Circuler à nouveau.', 'Forcément laisser passer un autre véhicule.'], 'Deixar de + infinitif marque l’arrêt d’une action.'),
      q(['A «Mentre esperem, observem», quan observem?', 'Durant l’espera.', 'Només després de l’espera.', 'Abans i mai durant.'], ['Dans « Mentre esperem, observem », quand observons-nous ?', 'Pendant l’attente.', 'Seulement après l’attente.', 'Avant, et jamais pendant.'], 'Mentre relie deux actions qui ont lieu en même temps.')
    ]
  ]),
  make('catala-phrases', 'Català · phrases compliquées', '🧠', 'Retrouver le sujet, la condition et l’action.', ['CATALA'], [], '', [
    p('Trouver qui fait quoi dans une longue phrase', 'LE NOM → SA DESCRIPTION → SON ACTION', [
      'Dans **el vehicle que circula davant nostre frena**, le sujet est el vehicle. Le groupe que circula davant nostre précise lequel ; l’action principale est frena.',
      '**Que** peut relier un nom à sa description. Dans el conductor que ens segueix, il désigne le conducteur qui nous suit : ce n’est pas automatiquement une question « quoi ? ».',
      '**El qual / la qual / els quals / les quals** peuvent reprendre un nom déjà cité dans certaines constructions. Le genre et le nombre aident à retrouver ce nom.',
      'Dans **la via per la qual circulem**, per la qual signifie par laquelle. Le groupe précise la voie sur laquelle nous roulons, pas une autre route à rejoindre.',
      '**On** peut relier une description à un lieu : el lloc on ens aturem = l’endroit où nous nous arrêtons. Il ne demande pas toujours une réponse lorsqu’il apparaît dans une phrase.',
      '**Qui** peut désigner la personne qui fait l’action ; **a qui** la personne à qui elle est destinée. Dans avisem el conductor que espera, nous alertons le conducteur, et c’est lui qui attend.'
    ], 'Réduis la phrase à **sujet + verbe principal**, puis remets la description. « Le véhicule [qui roule devant nous] freine » devient d’abord « le véhicule freine ».', [['que ens segueix', 'qui nous suit'], ['per la qual', 'par laquelle'], ['a qui', 'à qui']], ['Le nom avant le relatif', 'Un relatif renvoie souvent à un nom cité juste avant. Dans la phrase ci-dessous, que circula davant décrit el vehicle ; frena reste le verbe principal.', 'El vehicle que circula davant nostre frena.', 'Le véhicule qui roule devant nous freine.']),
    p('Déplier les conditions, les négations et les exceptions', 'QUI ? → SI QUOI ? → FAIRE QUOI ?', [
      '**Si…**, suivi d’une phrase, pose une condition. Dans si no hi ha espai, esperem, la condition est l’absence de place et l’action est attendre.',
      '**Llevat que** signifie sauf si. Dans no entrarem llevat que ens autoritzin, l’interdiction d’entrer reste la règle ; l’autorisation est le cas qui peut la lever.',
      '**Tot i que / encara que** signifient bien que / même si selon la phrase. Ils présentent une circonstance qui ne supprime pas l’action principale : tot i que plou, esperem.',
      '**No… fins que…** signifie ne pas… jusqu’à ce que… Dans no sortim fins que arriba el conductor, on attend l’arrivée du conducteur avant de sortir.',
      '**No només… sinó també…** signifie non seulement… mais aussi… La phrase ajoute un deuxième élément ; elle ne rejette pas le premier.',
      'Face à deux conditions liées par **i**, vérifie les deux. Dans només si tenim lloc i veiem bé, il faut avoir de la place **et** bien voir ; une seule condition ne suffit pas.'
    ], 'Trace trois cases mentales : **condition → action → exception**. Une négation au début peut rester valable jusqu’à la fin : n’arrête pas ta lecture au premier mot qui semble autoriser.', [['llevat que', 'sauf si'], ['fins que', 'jusqu’à ce que'], ['no només… sinó també…', 'non seulement… mais aussi…']], ['Lire jusqu’au dernier connecteur', 'Les mots si, i, llevat que ou fins que déterminent quand l’action est possible. Repère leur portée avant de traduire : un détail en fin de phrase peut changer toute la réponse.', 'Només actuarem si tenim lloc i veiem bé.', 'Nous agirons seulement si nous avons de la place et si nous voyons bien.'])
  ], [
    [
      q(['A «El vehicle que circula davant nostre frena», quina és l’acció principal?', 'Frenar.', 'Circular darrere nostre.', 'Aparcar.'], ['Dans « El vehicle que circula davant nostre frena », quelle est l’action principale ?', 'Freiner.', 'Rouler derrière nous.', 'Se garer.'], 'La description que circula davant nostre identifie le véhicule ; frena donne l’action principale.'),
      q(['A «El conductor que ens segueix s’atura», qui s’atura?', 'El conductor que va darrere nostre.', 'Nosaltres necessàriament.', 'Un vianant.'], ['Dans « El conductor que ens segueix s’atura », qui s’arrête ?', 'Le conducteur qui nous suit.', 'Forcément nous.', 'Un piéton.'], 'Le sujet reste el conductor, précisé par que ens segueix.'),
      q(['A «La via per la qual circulem és estreta», què és estret?', 'La via on circulem.', 'El nostre cinturó.', 'Una via que no utilitzem.'], ['Dans « La via per la qual circulem és estreta », qu’est-ce qui est étroit ?', 'La voie sur laquelle nous roulons.', 'Notre ceinture.', 'Une voie que nous n’utilisons pas.'], 'Per la qual renvoie à la via et indique où nous circulons.'),
      q(['A «Els vehicles, els quals estan aturats, ocupen el carril», què reprèn «els quals»?', 'Els vehicles.', 'El carril.', 'El conductor sol.'], ['Dans « Els vehicles, els quals estan aturats, ocupen el carril », que reprend « els quals » ?', 'Les véhicules.', 'La voie.', 'Le conducteur seul.'], 'Els quals est masculin pluriel comme els vehicles.'),
      q(['A «El lloc on ens aturem és segur», què introdueix «on»?', 'El lloc de l’aturada.', 'La causa d’una avaria.', 'El nombre de passatgers.'], ['Dans « El lloc on ens aturem és segur », que précise « on » ?', 'Le lieu de l’arrêt.', 'La cause d’une panne.', 'Le nombre de passagers.'], 'On relie la description à un lieu physique : el lloc.'),
      q(['A «Avisem el conductor que espera», qui espera?', 'El conductor.', 'Sempre nosaltres.', 'El vehicle sense conductor.'], ['Dans « Avisem el conductor que espera », qui attend ?', 'Le conducteur.', 'Toujours nous.', 'Le véhicule sans conducteur.'], 'Nous faisons l’action d’alerter ; que espera décrit le conducteur alerté.'),
      q(['A «La persona a qui donem l’avís escolta», qui rep l’avís?', 'La persona esmentada.', 'Nosaltres mateixos sempre.', 'Cap persona.'], ['Dans « La persona a qui donem l’avís escolta », qui reçoit l’alerte ?', 'La personne mentionnée.', 'Toujours nous-mêmes.', 'Personne.'], 'A qui identifie le destinataire de l’action : la personne à qui nous donnons l’alerte.')
    ], [
      q(['Segons «Si no hi ha espai, esperem», què fem quan falta espai?', 'Esperem.', 'Entrem igualment.', 'Deixem d’esperar sempre.'], ['Selon « Si no hi ha espai, esperem », que faisons-nous quand il manque de la place ?', 'Nous attendons.', 'Nous entrons quand même.', 'Nous cessons toujours d’attendre.'], 'L’absence de place est la condition ; attendre est la réponse donnée par cette phrase.'),
      q(['Segons «No entrarem llevat que ens autoritzin», sense autorització…', 'No entrarem.', 'Entrarem sempre.', 'Ja hem entrat.'], ['Selon « No entrarem llevat que ens autoritzin », sans autorisation…', 'Nous n’entrerons pas.', 'Nous entrerons toujours.', 'Nous sommes déjà entrés.'], 'Llevat que introduit une exception ; sans elle, la négation reste valable.'),
      q(['A «Tot i que plou, esperem aquí», la pluja impedeix l’espera?', 'No, la frase diu que esperem igualment.', 'Sí, la frase diu que marxem.', 'La frase no parla de pluja.'], ['Dans « Tot i que plou, esperem aquí », la pluie empêche-t-elle l’attente ?', 'Non, la phrase dit que nous attendons malgré tout.', 'Oui, la phrase dit que nous partons.', 'La phrase ne parle pas de pluie.'], 'Tot i que introduit une circonstance qui n’annule pas l’action annoncée.'),
      q(['Segons «No sortim fins que arriba el conductor», podem sortir abans que arribi?', 'No, segons aquesta frase.', 'Sí, és el que demana.', 'Només si el conductor no ve mai.'], ['Selon « No sortim fins que arriba el conductor », pouvons-nous sortir avant son arrivée ?', 'Non, selon cette phrase.', 'Oui, c’est ce qui est demandé.', 'Seulement si le conducteur ne vient jamais.'], 'No… fins que maintient l’attente jusqu’à l’événement annoncé.'),
      q(['«Revisem no només els llums, sinó també els frens.» Què revisem?', 'Els llums i els frens.', 'Només els frens.', 'Ni els llums ni els frens.'], ['« Revisem no només els llums, sinó també els frens. » Que vérifions-nous ?', 'Les feux et les freins.', 'Seulement les freins.', 'Ni les feux ni les freins.'], 'No només… sinó també ajoute un deuxième élément au premier.'),
      q(['«Només actuarem si tenim lloc i veiem bé.» Tenim lloc però no veiem bé. Es compleixen les condicions?', 'No, en falta una.', 'Sí, una condició és suficient.', 'Sí, perquè «i» significa «o».'], ['« Només actuarem si tenim lloc i veiem bé. » Nous avons de la place mais ne voyons pas bien. Les conditions sont-elles remplies ?', 'Non, il en manque une.', 'Oui, une condition suffit.', 'Oui, car « i » signifie « ou ».'], 'I = et : les deux conditions doivent être remplies.'),
      q(['«Encara que el vehicle sigui petit, cal comprovar l’espai.» Què continua sent necessari?', 'Comprovar l’espai.', 'Comprar un vehicle gran.', 'No mirar mai l’espai.'], ['« Encara que el vehicle sigui petit, cal comprovar l’espai. » Qu’est-ce qui reste nécessaire ?', 'Vérifier l’espace.', 'Acheter un grand véhicule.', 'Ne jamais regarder l’espace.'], 'Encara que ne supprime pas l’obligation exprimée par cal.')
    ]
  ])
];
