// In source answer order, never display order. Keep the Catalan words being
// tested inside quotes in language questions so the translation remains useful.
type FrenchQuestion = [question: string, correct: string, wrong1: string, wrong2: string];
export const frenchQuestions: Record<string, FrenchQuestion[]> = {
  routes: [
    ['Sans autre signalisation, quelle est la limite générale sur une route générale ?', '90 km/h.', '60 km/h.', '120 km/h.'],
    ['Quelle est la limite générale sur une route secondaire ?', '60 km/h.', '90 km/h.', '80 km/h.'],
    ['En agglomération, hors zones particulières, quelle est la limite générale ?', '50 km/h.', '60 km/h.', '90 km/h.'],
    ['Quelle vitesse maximale indique une zone 20 ?', '20 km/h.', '30 km/h.', '50 km/h.'],
    ['De quel côté doit-on circuler en règle générale ?', 'À droite.', 'À gauche.', 'Au centre.'],
    ['Sur une chaussée à double sens avec trois voies, à quoi sert la voie centrale ?', 'À dépasser ou à tourner à gauche.', 'À stationner.', 'À y circuler en permanence.'],
    ['Quelle partie de la voie est destinée aux piétons ?', 'Le trottoir.', 'La voie de circulation.', 'La chaussée.'],
    ['Qu’est-ce que le temps de réaction ?', 'Le temps entre percevoir le danger et commencer à freiner.', 'Le temps pendant lequel le véhicule est stationné.', 'Uniquement le temps de freinage.'],
    ['Quand commence la distance de freinage ?', 'Quand on commence à freiner.', 'Quand on voit le danger.', 'Quand le véhicule est déjà arrêté.'],
    ['La distance d’arrêt est la somme de…', 'La distance de réaction et la distance de freinage.', 'La longueur et la largeur du véhicule.', 'La vitesse et le temps de stationnement.'],
    ['Si la vitesse augmente, que devient la distance d’arrêt ?', 'Elle augmente.', 'Elle diminue toujours.', 'Elle ne change pas.'],
    ['Sous la pluie, comment adapter la distance de sécurité ?', 'L’augmenter.', 'La réduire.', 'La supprimer si les freins sont bons.'],
    ['Avec peu de visibilité, il faut pouvoir s’arrêter…', 'Dans la zone visible.', 'Après la zone visible.', 'Seulement si un panneau l’indique.'],
    ['Quel effet la fatigue peut-elle avoir ?', 'Allonger le temps de réaction.', 'Toujours réduire la distance de freinage.', 'Améliorer l’attention.'],
  ],
  priorites: [
    ['Un agent ordonne de s’arrêter et le feu est vert. Que faut-il faire ?', 'S’arrêter.', 'Continuer parce que le feu est vert.', 'Suivre uniquement les marques au sol.'],
    ['Qu’est-ce qui prime sur les feux tricolores ?', 'La signalisation temporaire qui modifie l’utilisation de la voie.', 'Les marques au sol.', 'N’importe quel panneau vertical.'],
    ['Entre un feu tricolore et un panneau vertical contradictoires, lequel prime ?', 'Le feu tricolore.', 'Le panneau vertical.', 'Toujours le plus ancien.'],
    ['Deux signaux du même type se contredisent. Lequel prime ?', 'Le plus restrictif.', 'Le moins restrictif.', 'Celui que le conducteur préfère.'],
    ['Devant un STOP, suffit-il de ralentir ?', 'Non, il faut s’arrêter complètement.', 'Oui, si personne n’arrive.', 'Oui, pendant la journée.'],
    ['Devant un cédez-le-passage, quand doit-on s’arrêter ?', 'Quand c’est nécessaire pour céder le passage.', 'Toujours pendant dix secondes.', 'Jamais.'],
    ['Peut-on entrer dans un carrefour si l’on risque d’y rester bloqué ?', 'Non, il faut attendre.', 'Oui, si l’on est prioritaire.', 'Oui, si l’on met le clignotant.'],
    ['À un carrefour sans signalisation, à qui cède-t-on généralement le passage ?', 'À celui qui vient de droite.', 'À celui qui vient de gauche.', 'Au véhicule le plus rapide.'],
    ['Dans un rond-point sans indication contraire, qui est prioritaire ?', 'Celui qui circule déjà à l’intérieur.', 'Celui qui y entre.', 'Celui qui a le plus gros véhicule.'],
    ['Quel mot signifie aussi « rotonda » (rond-point) ?', 'Glorieta (rond-point).', 'Voral (accotement).', 'Pendent (pente).'],
    ['En tournant, des piétons traversent la voie où l’on entre, sans passage marqué. Que faire ?', 'Leur céder le passage.', 'Passer avant eux puisqu’il n’y a pas de marquage.', 'Klaxonner et continuer.'],
    ['Devant un passage piéton où des personnes traversent, que faut-il faire ?', 'Les laisser passer.', 'Accélérer.', 'Les obliger à attendre au milieu.'],
    ['Un ballon arrive sur la chaussée. Que faut-il prévoir ?', 'Qu’un enfant puisse surgir derrière.', 'Que la route sera vide.', 'Qu’il faut dépasser immédiatement.'],
    ['Près d’une école avec des enfants, comment doit-on conduire ?', 'Avec davantage de prudence et une vitesse adaptée.', 'Plus vite pour passer rapidement.', 'Sans surveiller les trottoirs.'],
  ],
  manoeuvres: [
    ['Quand doit-on régler le siège et les rétroviseurs ?', 'Avant de démarrer.', 'Pendant que l’on tourne.', 'Seulement après un accident.'],
    ['Avant de tourner, quelle circulation doit-on observer ?', 'Celle de devant, de derrière et des côtés.', 'Uniquement celle de devant.', 'Uniquement les véhicules stationnés.'],
    ['Le clignotant donne-t-il la priorité ?', 'Non, il annonce seulement l’intention.', 'Oui, toujours.', 'Oui, si on l’allume tôt.'],
    ['Quand doit-on signaler un changement de direction ?', 'Suffisamment à l’avance.', 'Seulement après avoir tourné.', 'Quand on occupe déjà l’autre voie.'],
    ['Que doit-on vérifier concernant les véhicules qui approchent ?', 'Leur vitesse et leur distance.', 'Seulement leur couleur.', 'Seulement leur marque.'],
    ['Que signifie faire un « canvi de sentit » ?', 'Repartir dans le sens opposé.', 'Tourner légèrement le volant sans changer de sens.', 'Changer de rapport.'],
    ['Qu’est-ce qu’un angle mort ?', 'Une zone que l’on ne voit pas dans les rétroviseurs.', 'Une voie réservée.', 'Un panneau d’interdiction.'],
    ['Lors d’une insertion, à qui doit-on céder le passage ?', 'Aux véhicules qui circulent déjà sur la voie.', 'Seulement à ceux qui klaxonnent.', 'À personne si le clignotant est allumé.'],
    ['À quoi sert la voie d’accélération ?', 'À adapter sa vitesse avant de s’insérer.', 'À stationner.', 'À nous donner automatiquement la priorité.'],
    ['Quelle voie facilite la sortie et le ralentissement ?', 'La voie de décélération.', 'La voie d’accélération.', 'La voie du sens opposé.'],
    ['Sans autorisation expresse, peut-on faire demi-tour dans un tunnel ?', 'Non.', 'Oui, s’il fait jour.', 'Oui, si le tunnel est éclairé.'],
    ['Peut-on faire demi-tour dans un virage sans visibilité ?', 'Non.', 'Oui, avec les feux de détresse.', 'Oui, si l’on va très vite.'],
    ['Lors d’une manœuvre nécessaire, quelle distance doit-on parcourir en marche arrière ?', 'Le strict minimum indispensable.', 'Toujours cinquante mètres.', 'N’importe quelle distance.'],
    ['Une personne approche pendant une marche arrière. Que faut-il faire en cas de risque ?', 'S’arrêter immédiatement.', 'Continuer sans regarder.', 'Accélérer pour finir plus vite.'],
  ],
  depassements: [
    ['De quel côté dépasse-t-on en règle générale ?', 'Par la gauche.', 'Par la droite.', 'Par l’accotement.'],
    ['Avant de dépasser, faut-il observer les véhicules derrière soi ?', 'Oui.', 'Non, seulement ceux de devant.', 'Seulement la nuit.'],
    ['Quel espace doit-on prévoir avant de dépasser ?', 'L’espace nécessaire pour passer et se rabattre sans danger.', 'Uniquement l’espace à côté du véhicule.', 'Uniquement la longueur de notre véhicule.'],
    ['Peut-on empiéter sur le sens opposé pour dépasser sans visibilité suffisante ?', 'Non.', 'Oui, avec le clignotant.', 'Oui, si le véhicule est lent.'],
    ['Un véhicule derrière nous est déjà en train de nous dépasser. Peut-on se déporter pour dépasser ?', 'Non, il faut attendre.', 'Oui, nous sommes prioritaires.', 'Oui, si nous accélérons.'],
    ['La manœuvre prévue n’est plus sûre. Que doit-on faire ?', 'Renoncer au dépassement.', 'La terminer à tout prix.', 'Klaxonner et continuer.'],
    ['Qu’exprime « hem de comprovar » ?', 'Une obligation de vérifier.', 'Une interdiction de vérifier.', 'Une action déjà terminée.'],
    ['Quand on nous dépasse, peut-on accélérer pour empêcher la manœuvre ?', 'Non.', 'Oui, toujours.', 'Oui, si l’on roule sous la limite.'],
    ['Avant de revenir à droite, quel écart minimal faut-il laisser ?', 'Le double de la longueur du véhicule dépassé.', 'Un mètre.', 'La moitié de la longueur du véhicule dépassé.'],
    ['Un véhicule s’est arrêté pour laisser passer des piétons. Peut-on le dépasser ?', 'Non.', 'Oui, si l’on ne voit personne.', 'Oui, par n’importe quel côté.'],
    ['L’espace manque pour laisser un écart sûr avec un vélo. Que faire ?', 'Attendre.', 'Passer en le frôlant.', 'L’obliger à monter sur le trottoir.'],
    ['En ville, quand peut-on dépasser par la droite selon l’exception étudiée ?', 'Avec au moins deux voies dans le même sens et sans danger.', 'Dès qu’il y a un accotement.', 'Dans n’importe quelle rue à double sens.'],
    ['Que signifie « almenys dos carrils » ?', 'Deux voies ou plus.', 'Une seule voie.', 'Moins de deux voies.'],
    ['Hors agglomération, quel écart latéral minimal faut-il laisser en dépassant un vélo ?', '1,5 mètre.', '1 mètre.', '0,5 mètre.'],
  ],
  stationnement: [
    ['On s’immobilise à cause d’un feu rouge. De quoi s’agit-il ?', 'D’une immobilisation imposée (detenció).', 'D’un stationnement volontaire.', 'D’une opération de chargement.'],
    ['On s’arrête pour laisser descendre un passager. De quoi s’agit-il ?', 'D’un arrêt volontaire (parada).', 'D’une immobilisation pour panne.', 'D’un dépassement.'],
    ['On laisse le véhicule garé pendant une visite. De quoi s’agit-il ?', 'D’un stationnement.', 'D’un arrêt pour décharger.', 'D’une insertion.'],
    ['Une panne nous oblige à immobiliser le véhicule. Quel terme correspond ?', 'Detenció (immobilisation imposée).', 'Avançament (dépassement).', 'Canvi de sentit (demi-tour).'],
    ['Sur une chaussée à double sens, de quel côté s’arrête-t-on normalement ?', 'À droite.', 'À gauche.', 'Au centre.'],
    ['Dans une rue à sens unique, peut-on stationner à gauche si l’emplacement le permet ?', 'Oui, aussi à gauche.', 'Non, jamais.', 'Seulement au centre.'],
    ['Peut-on s’arrêter si cela crée un danger pour les autres ?', 'Non.', 'Oui, si c’est bref.', 'Oui, avec les feux de détresse.'],
    ['Peut-on stationner dans un tunnel ?', 'Non.', 'Oui, avec les feux de position.', 'Oui, de jour.'],
    ['Peut-on stationner sur un arrêt réservé aux transports publics ?', 'Non.', 'Oui, s’il n’y a pas de bus.', 'Oui, pendant toute la nuit.'],
    ['Sans restriction locale plus courte, quelle durée maximale continue s’applique au même endroit de la voie publique ?', '15 jours.', '7 jours.', '30 jours.'],
    ['En montée, avec une boîte manuelle, que doit-on ajouter au frein de stationnement ?', 'La première vitesse engagée.', 'Le point mort.', 'Les feux de route.'],
    ['En descente, avec une boîte manuelle, quel rapport engage-t-on avec le frein de stationnement ?', 'La marche arrière.', 'Le point mort.', 'La troisième vitesse.'],
    ['Avant d’ouvrir une portière, que doit-on vérifier ?', 'Que l’on ne met pas d’autres usagers en danger.', 'Seulement si le moteur est chaud.', 'Seulement l’heure.'],
    ['En quittant une place de stationnement, que faut-il faire ?', 'Observer, signaler et céder le passage.', 'S’engager sans regarder.', 'Compter sur le clignotant pour avoir la priorité.'],
  ],
  eclairage: [
    ['Quelle est la fonction principale des feux de position ?', 'Rendre le véhicule visible.', 'Éclairer très loin.', 'Indiquer un demi-tour.'],
    ['Quels sont les « llums d’encreuament » ?', 'Les feux utilisés pour ne pas éblouir quand on croise un véhicule.', 'Les feux blancs de marche arrière.', 'Les clignotants.'],
    ['Nos feux de route risquent d’éblouir un véhicule. Que faire ?', 'Passer aux feux de croisement.', 'Garder les feux de route.', 'Éteindre tous les feux.'],
    ['L’autre conducteur garde ses feux de route. Peut-on l’éblouir à notre tour ?', 'Non.', 'Oui, pour l’obliger à changer.', 'Oui, si l’on roule plus lentement.'],
    ['Peut-on garder les feux de route avec le véhicule stationné ?', 'Non.', 'Oui, toujours la nuit.', 'Oui, s’il n’y a pas de trottoir.'],
    ['De quelle couleur est le feu de marche arrière ?', 'Blanc.', 'Rouge.', 'Bleu.'],
    ['Quand faut-il éteindre le clignotant ?', 'Quand la manœuvre se termine.', 'Avant de commencer à tourner.', 'Jamais pendant le trajet.'],
    ['On entre de jour dans un tunnel éclairé. Quels feux faut-il au minimum ?', 'Les feux de croisement.', 'Aucun feu.', 'Seulement les feux de position.'],
    ['Quel éclairage une moto doit-elle utiliser de jour ?', 'Les feux de croisement.', 'Seulement les feux de position.', 'Aucun s’il fait soleil.'],
    ['Une pluie légère justifie-t-elle toujours le feu antibrouillard arrière ?', 'Non.', 'Oui.', 'Seulement en agglomération.'],
    ['Quand utilise-t-on le feu antibrouillard arrière ?', 'Dans des conditions particulièrement défavorables.', 'Chaque nuit.', 'Dès qu’il y a un nuage.'],
    ['La nuit, il faut pouvoir s’arrêter…', 'Dans la zone éclairée que l’on voit.', 'Au-delà de la zone visible.', 'Seulement avec les feux de route.'],
    ['Si l’on est ébloui, que doit-on faire ?', 'Ralentir et s’arrêter si nécessaire.', 'Accélérer.', 'Fixer les phares du regard.'],
    ['Le feu à l’entrée d’un tunnel est rouge. Peut-on entrer avec notre voiture ?', 'Non.', 'Oui, si les feux sont allumés.', 'Oui, s’il fait jour.'],
  ],
  meteo: [
    ['Sous la pluie, que devient généralement l’adhérence ?', 'Elle diminue.', 'Elle augmente toujours.', 'Elle ne change jamais.'],
    ['Pourquoi faut-il se méfier des premières gouttes ?', 'La chaussée peut être très glissante.', 'Les freins deviennent inutiles.', 'L’adhérence augmente.'],
    ['Que se passe-t-il lors d’un aquaplaning ?', 'L’eau fait perdre au pneu le contact avec la chaussée.', 'Le moteur refroidit trop.', 'Le véhicule freine mieux.'],
    ['Quelle conduite adopter sur une chaussée couverte d’eau ?', 'Une conduite douce, à vitesse réduite.', 'Des freinages brusques.', 'Des coups de volant soudains.'],
    ['Dans le brouillard, peut-on se rapprocher fortement du véhicule devant pour le suivre ?', 'Non, il faut garder davantage de distance.', 'Oui, toujours.', 'Oui, si ses feux sont allumés.'],
    ['Par fort vent latéral, que peut-il arriver à la sortie d’une zone abritée ?', 'La trajectoire du véhicule peut changer.', 'Le vent disparaît.', 'La stabilité s’améliore toujours.'],
    ['Quelle chaussée est « molla » ?', 'Celle qui est mouillée.', 'Celle qui est sèche.', 'Celle qui est fermée.'],
    ['Sur la neige ou le verglas, comment adapter la distance de sécurité ?', 'On l’augmente.', 'On la réduit.', 'On la garde toujours identique.'],
    ['Sur le verglas, comment agir sur les commandes ?', 'Avec douceur.', 'Brusquement.', 'Toujours à fond.'],
    ['Quand faut-il ralentir pour prendre un virage ?', 'Avant d’y entrer.', 'Seulement au milieu.', 'Seulement après en être sorti.'],
    ['En descente, est-il correct de rouler au point mort ?', 'Non, il faut garder le frein moteur avec un rapport adapté.', 'Oui, pour toujours économiser.', 'Oui, si la descente est longue.'],
    ['Du 1er novembre au 15 mai, sans pneus hiver ni M+S, que faut-il emporter ?', 'Des chaînes prêtes à être utilisées.', 'Seulement une pelle.', 'Rien s’il fait beau aujourd’hui.'],
    ['Peut-on utiliser des chaînes sur une chaussée sans neige ni glace ?', 'Non.', 'Oui, toujours.', 'Oui, seulement en ville.'],
    ['Quel mot désigne la glace ou le verglas sur la route ?', 'Glace (« gel »).', 'Vent.', 'Brouillard.'],
  ],
  vigilance: [
    ['Quel effet la fatigue peut-elle avoir sur la conduite ?', 'Réduire l’attention.', 'Améliorer les réflexes.', 'Rendre les pauses inutiles.'],
    ['Nous avons sommeil au volant. Que faire ?', 'Trouver un endroit sûr et se reposer.', 'Monter la musique et continuer dans tous les cas.', 'Accélérer pour arriver plus tôt.'],
    ['Ouvrir la fenêtre remplace-t-il le repos ?', 'Non.', 'Oui, toujours.', 'Oui, la nuit.'],
    ['Regarder son téléphone en conduisant peut…', 'Retarder la détection d’un danger.', 'Améliorer l’attention portée à la route.', 'Toujours réduire le temps de réaction.'],
    ['Avant de conduire avec un nouveau médicament, que faire ?', 'Lire les avertissements et demander conseil.', 'Supposer qu’il n’affecte jamais la conduite.', 'En prendre davantage pour rester éveillé.'],
    ['Quel comportement aide les autres usagers ?', 'Annoncer ses manœuvres à temps.', 'Changer de trajectoire sans prévenir.', 'Freiner pour les surprendre.'],
    ['Que signifie « tinc son » ?', 'J’ai besoin de dormir.', 'Je suis très pressé.', 'J’entends un bruit.'],
    ['Quel est le taux maximal général d’alcool dans le sang ?', '0,5 g/l.', '0,8 g/l.', '1,0 g/l.'],
    ['Quel taux s’applique aux catégories soumises au taux zéro ?', '0,0 g/l.', '0,5 g/l.', '0,8 g/l.'],
    ['Une petite dose d’alcool peut-elle nuire à la conduite ?', 'Oui.', 'Non, jamais.', 'Seulement si l’on conduit la nuit.'],
    ['Le taux général autorisé est-il de 0,8 g/l ?', 'Non.', 'Oui.', 'Seulement pendant le week-end.'],
    ['Après un accident, le contrôle se limite-t-il toujours au conducteur présumé responsable ?', 'Non, il peut concerner tout usager impliqué.', 'Oui.', 'Seuls les professionnels sont contrôlés.'],
    ['Si l’on conteste le résultat de l’éthylomètre, que peut-on demander ?', 'Une analyse de sang de contrôle.', 'L’annulation automatique du test.', 'Qu’un passager décide.'],
    ['Que signifie « no superior a » ?', 'Une limite maximale.', 'Une limite minimale.', 'Une quantité sans limite.'],
  ],
  vehicule: [
    ['Quel est le rôle de la transmission ?', 'Transmettre le mouvement du moteur aux roues motrices.', 'Éclairer la route.', 'Laver le pare-brise.'],
    ['Quand la pédale d’embrayage est enfoncée, le moteur est…', 'Débrayé.', 'Embrayé.', 'Forcément éteint.'],
    ['Quelles roues reçoivent la force du moteur ?', 'Les roues motrices.', 'Seulement les roues de secours.', 'Toujours toutes, sans exception.'],
    ['Quel est le rôle des roues directrices ?', 'Orienter la trajectoire.', 'Éclairer les virages.', 'Stocker du carburant.'],
    ['Quel frein immobilise le véhicule stationné ?', 'Le frein de stationnement.', 'Uniquement le frein moteur.', 'L’embrayage.'],
    ['Comment vérifie-t-on habituellement la pression des pneus ?', 'À froid, selon les indications du constructeur.', 'Toujours à chaud et au hasard.', 'Seulement lorsqu’ils sont à plat.'],
    ['Si l’on détecte des vibrations ou une usure irrégulière, que faire ?', 'Faire contrôler le véhicule.', 'Les ignorer.', 'Toujours gonfler à la pression maximale.'],
    ['Qu’est-ce qui favorise une conduite économique ?', 'Anticiper et éviter les accélérations inutiles.', 'Accélérer et freiner constamment.', 'Toujours rouler en première.'],
    ['Quand le moteur le permet, quel rapport favorise une conduite économique ?', 'Un rapport plus long, adapté.', 'Toujours la première vitesse.', 'Toujours le point mort.'],
    ['Pour l’aérodynamisme, où vaut-il mieux placer les bagages ?', 'Dans le coffre.', 'Sur la galerie de toit.', 'À l’extérieur des fenêtres.'],
    ['Une charge inutile peut…', 'Augmenter la consommation.', 'Supprimer la consommation.', 'Toujours améliorer le freinage.'],
    ['Est-il sûr de descendre un col avec le contact coupé ?', 'Non.', 'Oui, pour économiser du carburant.', 'Oui, si la route est droite.'],
    ['Pourquoi garder un rapport adapté en descente ?', 'Pour disposer du frein moteur.', 'Pour supprimer l’adhérence.', 'Pour n’avoir besoin d’aucun contrôle.'],
    ['Une utilisation continue et excessive des freins peut provoquer…', 'Une surchauffe et une perte d’efficacité.', 'Une amélioration permanente des freins.', 'Davantage de carburant dans le réservoir.'],
  ],
  transport: [
    ['Dans une voiture équipée, qui doit porter la ceinture, hors exemptions légales ?', 'Le conducteur et tous les passagers.', 'Seulement le conducteur.', 'Seulement les occupants à l’avant.'],
    ['Sur une voie urbaine, la ceinture cesse-t-elle d’être obligatoire ?', 'Non.', 'Oui, toujours.', 'Oui, aux places avant.'],
    ['La règle générale étudiée pour le siège enfant combine…', 'Moins de 10 ans et moins de 1,50 m.', 'Seulement la couleur du véhicule.', 'Plus de 18 ans et plus de 1,80 m.'],
    ['Dans une voiture de neuf places maximum, où s’installe normalement l’enfant concerné par cette règle ?', 'À l’arrière, avec un dispositif adapté.', 'À l’avant, sans dispositif de retenue.', 'Dans le coffre.'],
    ['À quoi le dispositif de retenue pour enfant doit-il être adapté ?', 'À la taille et au poids.', 'Seulement à la couleur des sièges.', 'Seulement au prix de la voiture.'],
    ['Sur une moto ordinaire, comment doit-on porter le casque ?', 'Correctement attaché.', 'Non attaché.', 'Suspendu au bras.'],
    ['Peut-on dépasser le nombre de places autorisées si le trajet est court ?', 'Non.', 'Oui.', 'Oui, si les passagers sont adultes.'],
    ['Comment la charge doit-elle être transportée ?', 'Bien fixée pour ne pas bouger ni tomber.', 'Libre de bouger dans les virages.', 'Retenue uniquement par le passager.'],
    ['La charge peut-elle réduire la visibilité du conducteur ?', 'Non.', 'Oui, si elle est légère.', 'Oui, en ville.'],
    ['Peut-on masquer la plaque avec des bagages bien attachés ?', 'Non.', 'Oui, s’ils sont bien attachés.', 'Oui, seulement de jour.'],
    ['Que doit-on respecter en chargeant le véhicule ?', 'Les masses et dimensions autorisées.', 'Seulement la capacité du coffre.', 'Seulement le nombre de sacs.'],
    ['Pendant le chargement ou le déchargement, comment doit être le moteur ?', 'Arrêté.', 'En accélération.', 'Toujours en marche.'],
    ['Si l’on doit décharger sur la voie publique, quel côté privilégier ?', 'Le côté le plus proche du trottoir.', 'Le centre de la chaussée.', 'Le côté de la circulation qui arrive.'],
    ['Quelle dimension indique « amplada » ?', 'La largeur du véhicule.', 'La longueur.', 'Le poids.'],
  ],
  documents: [
    ['Quel document autorise une personne à conduire une catégorie de véhicules ?', 'Le permis de conduire.', 'Seulement l’assurance.', 'Seulement le certificat d’immatriculation.'],
    ['Quel document identifie administrativement le véhicule ?', 'Le certificat d’immatriculation.', 'La carte d’un passager.', 'L’ordonnance médicale.'],
    ['Que couvre l’assurance obligatoire de responsabilité civile ?', 'Les dommages causés aux tiers.', 'Toujours toutes les pannes de son propre véhicule.', 'Seulement le carburant.'],
    ['Que signifie ITV ?', 'Inspection technique des véhicules.', 'Taxe de transport de voyageurs.', 'Indicateur de trajectoire variable.'],
    ['L’assurance remplace-t-elle le permis de conduire ?', 'Non.', 'Oui, si elle est valide.', 'Oui, en ville.'],
    ['Quelle assurance faut-il pouvoir justifier ?', 'Une assurance en cours de validité.', 'Une assurance expirée.', 'Celle d’un autre véhicule sans rapport.'],
    ['Que signifie « ITV, si escau » ?', 'Le contrôle technique lorsqu’il est exigible pour le véhicule.', 'Le contrôle technique seulement si le conducteur le souhaite.', 'Le contrôle technique n’est jamais obligatoire.'],
    ['Avec le permis B, quel est le nombre maximal de personnes ?', '9, conducteur compris.', '10, conducteur compris.', '9 passagers plus le conducteur.'],
    ['Dans un véhicule de neuf places, conducteur à bord, combien de passagers peuvent monter au maximum ?', '8.', '9.', '10.'],
    ['Que signifie MMA ?', 'Masse maximale autorisée.', 'Masse minimale conseillée.', 'Mesure maximale de largeur.'],
    ['Le poids à vide et la MMA sont-ils forcément identiques ?', 'Non.', 'Oui, toujours.', 'Oui, si le véhicule est neuf.'],
    ['Avant de tracter une remorque, que vérifier ?', 'Que le permis et l’ensemble de véhicules le permettent.', 'Seulement que la remorque est de la même couleur.', 'Seulement qu’il fait jour.'],
    ['Un document périmé est-il en cours de validité ?', 'Non.', 'Oui.', 'Seulement en agglomération.'],
    ['Avec un contrôle technique valide, peut-on contrôler les émissions du véhicule ?', 'Oui.', 'Non, jamais.', 'Seulement si nous n’avons pas d’assurance.'],
  ],
  accidents: [
    ['En arrivant sur un accident, que faire en premier ?', 'Protéger sans créer un autre danger.', 'Se garer au milieu sans regarder.', 'Partir sans évaluer la situation.'],
    ['Si nous occupons la chaussée lors d’un accident, que devons-nous porter ?', 'Le gilet réfléchissant.', 'Des écouteurs.', 'Une couverture sur la tête.'],
    ['Qui doit-on prévenir s’il y a des blessés ?', 'Les services de secours ou la police.', 'Seulement un ami.', 'Seulement le garage.'],
    ['Quelles informations sont utiles lors de l’alerte ?', 'Le lieu, les dangers et le nombre de blessés.', 'Seulement la couleur des vêtements.', 'Seulement la marque du téléphone.'],
    ['Comment aider les blessés ?', 'En suivant les consignes et selon nos capacités.', 'En improvisant n’importe quelle manœuvre.', 'Sans écouter les services de secours.'],
    ['S’il y a des blessés, peut-on simplement partir après avoir donné son numéro ?', 'Non, il faut rester disponible sauf nécessité liée à l’aide.', 'Oui, toujours.', 'Oui, si nous sommes pressés.'],
    ['Quel ordre correspond à PAS ?', 'Protéger, alerter, secourir.', 'Accélérer, sortir, s’arrêter.', 'Secourir, partir, alerter.'],
    ['Quelle question demande le lieu de l’accident ?', 'Où ?', 'Combien ?', 'Quand ?'],
    ['Que signifie « ferit » ?', 'Une personne blessée.', 'Un véhicule garé.', 'Une route sèche.'],
    ['Que communique-t-on aux services de secours ?', 'Ce que l’on observe, en répondant à leurs questions.', 'Un diagnostic inventé.', 'Seulement que nous sommes pressés.'],
    ['À quelle distance minimale la présignalisation du danger doit-elle être visible ?', '100 mètres.', '10 mètres.', '25 mètres.'],
    ['« Visible à 100 m » signifie-t-il forcément « placé exactement à 100 m » ?', 'Non.', 'Oui.', 'Seulement de jour.'],
    ['Avec uniquement des dégâts matériels, quel est le délai maximal pour prévenir les assureurs ?', '8 jours calendaires.', '30 jours calendaires.', '15 jours ouvrables.'],
    ['Les jours calendaires incluent-ils les week-ends ?', 'Oui.', 'Non.', 'Seulement les samedis.'],
  ],
  'catala-pieges': [
    ['Quelle expression indique une obligation ?', 'Il faut s’arrêter.', 'Il n’est pas nécessaire de s’arrêter.', 'On peut s’arrêter.'],
    ['Que veut dire « no cal aturar-se » ?', 'Il n’est pas nécessaire de s’arrêter.', 'Il est interdit de s’arrêter.', 'Il est obligatoire de s’arrêter.'],
    ['Quelle phrase exprime une interdiction ?', 'On ne peut pas stationner.', 'Il n’est pas nécessaire de stationner.', 'On peut stationner.'],
    ['Quel mot signifie « seulement » ?', 'Seulement (« només »).', 'Toujours.', 'Tout le monde.'],
    ['Que veut dire « no hi ha cap vehicle » ?', 'Il n’y a pas de véhicules.', 'Il y a beaucoup de véhicules.', 'Il y a un véhicule devant.'],
    ['Quelle expression équivaut à « jamais » ?', 'En aucun cas.', 'Dans tous les cas.', 'Chaque jour.'],
    ['Dans « on peut le faire, à condition que ce soit sûr », qu’exprime « sempre que » ?', 'Une condition.', 'Une interdiction absolue.', 'Une action passée.'],
    ['Que signifie « fins a 50 » ?', '50 ou moins.', 'Seulement plus de 50.', 'Toujours exactement 50.'],
    ['Que signifie « almenys 50 » ?', '50 ou plus.', 'Moins de 50.', 'Seulement 49.'],
    ['Que signifie « massa ràpid » ?', 'Excessivement rapide.', 'Assez lent.', 'Pas du tout rapide.'],
    ['Quelle expression permet de demander la cause ?', 'Pourquoi ?', 'Par conséquent.', 'Vers.'],
    ['Quel connecteur introduit une explication de cause ?', 'Parce que.', 'Après.', 'Seulement.'],
    ['Quel connecteur introduit une conclusion ?', 'Par conséquent.', 'Avant de.', 'Sauf.'],
    ['Dans « tourner vers la droite », que veut dire « cap a » ?', 'En direction de.', 'Aucun véhicule.', 'La partie supérieure du corps.'],
  ],
  'catala-verbes': [
    ['Quel verbe a un sens proche de « aturar-se » (s’arrêter) ?', 'S’arrêter.', 'Accélérer.', 'Avancer.'],
    ['Quel verbe signifie vérifier ?', 'Vérifier (« comprovar »).', 'Acheter.', 'Courir.'],
    ['Quel verbe décrit un changement de direction ?', 'Tourner.', 'Stationner.', 'Dormir.'],
    ['Quel verbe est le contraire d’« augmenter » ?', 'Réduire.', 'Allumer.', 'Prévenir.'],
    ['Quel verbe est le contraire d’« allumer » ?', 'Éteindre.', 'Avancer.', 'Vérifier.'],
    ['Que signifie « acostar-se » ?', 'S’approcher.', 'S’éloigner.', 'Toujours stationner.'],
    ['Dans « aturar-nos », qui désigne « -nos » ?', 'Nous.', 'Seulement lui.', 'Personne.'],
    ['Quelle expression indique « nous avons l’obligation » ?', 'Nous devons.', 'Nous pouvons.', 'Ce n’est pas nécessaire.'],
    ['Quelle expression indique une possibilité ?', 'Nous pouvons.', 'Nous devons.', 'C’est interdit.'],
    ['Que veut dire « caldrà » ?', 'Ce sera nécessaire.', 'Ce n’est plus possible.', 'C’était interdit.'],
    ['Quelle action vient en premier dans « avant de tourner, nous regardons » ?', 'Regarder.', 'Tourner.', 'Toujours les deux en même temps.'],
    ['Que veut dire « hi ha un obstacle » ?', 'Il y a un obstacle.', 'Il n’y a aucun obstacle.', 'Nous avons supprimé l’obstacle.'],
    ['Quelle expression signifie « si c’est nécessaire » ?', 'Si nécessaire.', 'Sans.', 'Jamais.'],
    ['Dans « en nous approchant d’un carrefour, nous devons regarder », quelle action est obligatoire ?', 'Regarder.', 'Stationner.', 'Accélérer.'],
  ],
};
